name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Checkout repo
      uses: actions/checkout@v2
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - run: git --version
    - name: Build
      run: cargo build --release
    - name: Tests
      run: RUST_BACKTRACE=full cargo test --release
    - run: echo "This job's status is ${{ job.status }}."
