name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckoutRepo
      uses: actions/checkout@v2
    - name: Debug
      run: RUST_BACKTRACE=1 cargo test
    - name: Release
      run: RUST_BACKTRACE=1 cargo test --release
